ingress:
  enabled: true
  scheme: ""
  subnets: ""
  security_groups: "" #Load balancer Security Group
  dns_zone: ""
  certificate_arn: ""

image:
  name: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/discovery-ui
  tag: latest

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
