language: node_js
os: linux
node_js:
  - "10"
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
script:
  - npm run test
  - npm run start & wait-on http://localhost:9001
  - npm run cypress:run
before_deploy: npm run build:library
deploy:
- provider: npm
  email: "johnson.denen@gmail.com"
  api_token:
    secure: $NPM_AUTH_TOKEN
  on:
    tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/
