language: node_js
node_js:
  - "10"
script:
- npm run test
before_deploy: npm run build:library
deploy:
- provider: npm
  skip_cleanup: true
  email: "johnson.denen@gmail.com"
  api_key:
    secure: $NPM_AUTH_TOKEN
  on:
    tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/
